// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IntroController from "./intro_controller"
application.register("intro", IntroController)

import IssenController from "./issen_controller"
application.register("issen", IssenController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)
